name: iOS Build and Test

on:
  push:
    branches: [ main ]
    paths: [ 'ios_app/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'ios_app/**' ]
  workflow_dispatch:

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Cache derived data
      uses: actions/cache@v4
      with:
        path: ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-derived-data-${{ hashFiles('ios_app/**/*.swift') }}
        restore-keys: |
          ${{ runner.os }}-derived-data-
    
    - name: Build for Testing
      run: |
        cd ios_app/water-softener
        xcodebuild -scheme water-softener \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
          -derivedDataPath DerivedData \
          build-for-testing
          
    - name: Run Tests
      run: |
        cd ios_app/water-softener
        xcodebuild -scheme water-softener \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
          -derivedDataPath DerivedData \
          test-without-building

  archive:
    name: Archive and Export IPA
    runs-on: macos-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Import Code-Signing Certificates
      uses: Apple-Actions/import-codesign-certs@v2
      if: ${{ env.P12_PASSWORD != '' }}
      with:
        p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
        p12-password: ${{ secrets.P12_PASSWORD }}
      env:
        P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
    
    - name: Download Provisioning Profile
      uses: Apple-Actions/download-provisioning-profiles@v1
      if: ${{ env.PROVISIONING_PROFILE_BASE64 != '' }}
      with:
        bundle-id: bhackel.water-softener
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
      env:
        PROVISIONING_PROFILE_BASE64: ${{ secrets.PROVISIONING_PROFILE_BASE64 }}
        
    - name: Build and Archive
      run: |
        cd ios_app/water-softener
        xcodebuild -scheme water-softener \
          -archivePath water-softener.xcarchive \
          -destination 'generic/platform=iOS' \
          archive
          
    - name: Export IPA
      run: |
        cd ios_app/water-softener
        xcodebuild -exportArchive \
          -archivePath water-softener.xcarchive \
          -exportPath . \
          -exportOptionsPlist ExportOptions.plist
      
    - name: Rename to .tipa extension
      run: |
        cd ios_app/water-softener
        mv water-softener.ipa water-softener.tipa
        
    - name: Upload TIPA Artifact
      uses: actions/upload-artifact@v4
      with:
        name: water-softener-tipa
        path: ios_app/water-softener/water-softener.tipa
        retention-days: 30